// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8mOTATQT-lwVtbKyvMVc0tYqL-4OLjI',
    appId: '1:192178442232:web:31d6941d970168ef14900d',
    messagingSenderId: '192178442232',
    projectId: 'hafidtech-shopapp-ec812',
    authDomain: 'hafidtech-shopapp-ec812.firebaseapp.com',
    storageBucket: 'hafidtech-shopapp-ec812.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhSywWW3MOFpi6rLpWPqqPZLhCNnwbjE',
    appId: '1:192178442232:android:de7a12912cf384f414900d',
    messagingSenderId: '192178442232',
    projectId: 'hafidtech-shopapp-ec812',
    storageBucket: 'hafidtech-shopapp-ec812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHe1NLniJT4AYMXJ5-oIrYZm202p2c9Bc',
    appId: '1:192178442232:ios:22a1c201e863f7c214900d',
    messagingSenderId: '192178442232',
    projectId: 'hafidtech-shopapp-ec812',
    storageBucket: 'hafidtech-shopapp-ec812.firebasestorage.app',
    iosClientId: '192178442232-nqfj94usbi763m9juetuveu12rj9dops.apps.googleusercontent.com',
    iosBundleId: 'com.example.hfShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHe1NLniJT4AYMXJ5-oIrYZm202p2c9Bc',
    appId: '1:192178442232:ios:22a1c201e863f7c214900d',
    messagingSenderId: '192178442232',
    projectId: 'hafidtech-shopapp-ec812',
    storageBucket: 'hafidtech-shopapp-ec812.firebasestorage.app',
    iosClientId: '192178442232-nqfj94usbi763m9juetuveu12rj9dops.apps.googleusercontent.com',
    iosBundleId: 'com.example.hfShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc8mOTATQT-lwVtbKyvMVc0tYqL-4OLjI',
    appId: '1:192178442232:web:b14364212be85d0114900d',
    messagingSenderId: '192178442232',
    projectId: 'hafidtech-shopapp-ec812',
    authDomain: 'hafidtech-shopapp-ec812.firebaseapp.com',
    storageBucket: 'hafidtech-shopapp-ec812.firebasestorage.app',
  );
}
